services:
  - type: web
    name: campus-ignite
    runtime: python
    pythonVersion: 3.12.0
    rootDir: campus_ignite/backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn campus_ignite_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
