# Generated by Django 4.2.30 on 2026-09-16 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chairperson', 'Chairperson'), ('cell_leader', 'Cell Leader'), ('marketing_leader', 'Marketing Leader'), ('hospitality_leader', 'Hospitality Leader'), ('evangelism_leader', 'Evangelism Leader'), ('prayer_leader', 'Prayer Leader'), ('choir_leader', 'Choir Leader'), ('ignite_her', 'Ignite Her'), ('ignite_him', 'Ignite Him'), ('administration', 'Administration')], max_length=50, unique=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_of', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='leadership.leadershipposition')),
                ('second_in_cmd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_in_cmd_of', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position__sort_order'],
                'unique_together': {('position', 'year')},
            },
        ),
    ]
