# Generated by Django 4.2.30 on 2026-09-16 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadershipassignment',
            name='second_in_cmd_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_in_cmd_2_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
