# Generated by Django 4.2.30 on 2026-09-17 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leadership', '0002_leadershipassignment_second_in_cmd_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', 'user__first_name'],
            },
        ),
    ]
