# Generated by Django 4.2.30 on 2026-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('pastor', 'Pastor'), ('cell_leader', 'Cell Leader'), ('facilitator', 'Cell Facilitator'), ('leadership', 'Leadership Member'), ('chairperson', 'Chairperson'), ('admin', 'Administrator')], max_length=50, unique=True),
        ),
    ]
