# Generated by Django 4.2.30 on 2026-09-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_alumni',
            field=models.BooleanField(default=False),
        ),
    ]
