# Generated by Django 4.2.30 on 2026-08-15 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Newbie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=200)),
                ('year_of_study', models.CharField(choices=[('Part 1', 'Part 1'), ('Part 2', 'Part 2'), ('Part 3', 'Part 3'), ('Part 4', 'Part 4')], default='Part 1', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('following', 'Following Up'), ('connected', 'Connected to Cell')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_registered'],
            },
        ),
    ]
